19-Takify/19-taskify

src/components/Tag/Tag.module.scss, src/components/Tag/index.tsx
- #67
feat/tag -> develop
태그 컴포넌트 작성
css스타일이 부족할꺼 같아요
=> [feat] 태그 컴포넌트

vercel.json
- #74 
fix/vercel-rewrites-remove -> develop
- 현재 개발 배포 사이트에 생기는 404 페이지 및 로그인, 회원가입 페이지에 접속되지 않는 현상 해결입니다.
감사합니다.
=> [fix] vercel.json rewrites 삭제

src/components/SideMenu/index.tsx, src/pages/dashboard/[id]/edit/index.page.tsx
- #80 
feat/api-connect > develop
초대 불러오기 api 권한 이슈 수정
=> [fix] 초대 불러오기 api 권한 이슈 수정

public/svgs/next-button.svg, public/svgs/prev-button.svg, src/components/Button/PageButton/PageButton.module.scss, src/components/Card/index.tsx, src/components/Header/DashBoard/DashBoardHeader.module.scss, src/components/Header/DashBoard/index.tsx, src/components/Modal/Modal/Modal.module.scss, src/components/Profile/ProfileIcon/index.tsx, src/components/SideMenu/index.tsx, src/components/Tag/index.tsx, src/pages/dashboard/[id]/components/Column/Column.module.scss, src/pages/dashboard/[id]/components/Column/index.tsx, src/pages/dashboard/[id]/index.page.tsx, src/pages/mydashboard/index.page.tsx
- #82 
feat/carousel > develop
대시보드 페이지 캐러셀 추가
https://github.com/19-Takify/19-taskify/assets/162881886/07119519-7f0c-48ed-957f-d4ae537c044e
=> [feat] 캐러셀 추가

src/components/Header/DashBoard/DashBoardHeader.module.scss, src/components/Loading/Loading.module.scss, src/components/Loading/index.tsx, src/hooks/useRouterLoading.ts, src/pages/404.page.tsx, src/pages/dashboard/[id]/components/Column/Column.module.scss, src/pages/dashboard/[id]/components/Column/index.tsx, src/pages/dashboard/[id]/edit/index.page.tsx, src/pages/dashboard/[id]/index.page.tsx, src/pages/index.page.tsx, src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss, src/pages/mydashboard/components/InvitedDashboard/index.tsx, src/pages/mydashboard/index.page.tsx, src/pages/mypage/index.page.tsx
- #87 
fix/dashboard -> develop
자잘한 버그 수정하고 크게는 로딩 상태 추가했습니다
https://github.com/19-Takify/19-taskify/assets/162881886/f4dbfaee-0d7c-4368-ac99-5e51da51ab73
=> [fix]: 버그 수정 및 로딩 상태 추가

src/components/Button/BackButton/BackButton.module.scss, src/hooks/useRouterLoading.ts, src/pages/_app.page.tsx, src/pages/dashboard/[id]/edit/components/DashboardEdit/Dashboard.module.scss, src/pages/dashboard/[id]/edit/components/DashboardManager/index.tsx, src/pages/dashboard/[id]/edit/style/edit.page.module.scss, src/pages/mydashboard/myDashboard.module.scss
fix/dashboard > develop
스타일 수정
=> [fix] 스타일 수정

src/components/Button/BackButton/BackButton.module.scss, src/components/Button/PageButton/PageButton.module.scss, src/pages/dashboard/[id]/edit/style/edit.page.module.scss, src/pages/mypage/style/mypage.module.scss
fix/dashboard -> develop
스타일 수정
=> [fix] 스타일 수정

src/components/Modal/Comment/Comment.tsx
- #94 
fix/comment -> develop
댓글 수정 시 원래 값이 안 들어감
=> [fix] 댓글 수정 시 원래 값이 안 들어감

src/pages/login/index.page.tsx
- #96 
fix/loading
로그인 페이지 로딩 상태
=> [fix] 로그인 페이지 로딩 상태

src/components/Modal/Comment/Comment.module.scss, src/components/Modal/ToDoModal/ToDOModal.module.scss, src/components/Modal/ToDoModal/index.tsx
=> [chore] ToDoModal css 수정 / ToDo image 수정

src/components/SideMenu/index.tsx
fix/sidemenu > develop
사이드 메뉴 계속 열려있는 이슈 수정
=> [fix] 사이드 메뉴 계속 열려있는 이슈 수정

src/components/Modal/Comment/Comment.tsx, src/components/Modal/ToDoModal/index.tsx
- #26 
- 수정 클릭 시 textArea에 자동 포커스
=> [chore] 자잘한 에러 수정

src/components/Modal/InviteDashboardModal/index.tsx
=> [fix] 중복 초대 발송

src/components/Modal/NewDashboardModal/index.tsx
- #98
refactor/new-dashboard-move
대시보드 생성 후 생성된 대시보드로 이동
=> [refactor] 대시보드 생성 후 생성된 대시보드로 이동

src/components/Button/ModalButton/ModalButton.module.scss, src/components/Modal/NewDashboardModal/NewDashboardModal.module.scss
- #104 
style/button-disabled-styling
모달 버튼 disabled 스타일링
=> [style] ModalButton disabled 스타일링

src/pages/mydashboard/components/InvitedDashboard/index.tsx, src/pages/mydashboard/components/SearchDashboard/SearchDashboard.module.scss, src/pages/mydashboard/components/SearchDashboard/index.tsx, src/pages/mydashboard/index.page.tsx, src/pages/mydashboard/myDashboard.module.scss
- #91
feat/fix/invited-dashboard -> develop
나의 대시보드 페이지에 초대 기능이 문제 있어서 수정했습니다.
추가로 뒤로가기 버튼과 디자인 조금 수정했습니다.
수정 잘 반영됬는지 확인 부탁드립니다!
=> [fix] 초대 기능 수정

src/constants/pageUrl.ts, src/middleware.page.ts, src/utils/auth.ts
- #109 
fix/unauthorization-access -> develop
접근 권한 없이 대시보드 페이지 접속 시 redirect 작업 했습니다!
마지막까지 파이팅!!
=> [fix] 접근 권한 없이 대시보드 페이지 접속 시 에러

src/components/Card/Card.module.scss, src/components/Card/index.tsx, src/components/Modal/Comment/Comment.module.scss, src/components/Modal/ManageColumnModal/index.tsx, src/components/Modal/Modal/Modal.module.scss, src/components/Modal/ModalPopOver/index.tsx, src/components/Modal/ToDoModal/ToDOModal.module.scss, src/components/Modal/ToDoModal/index.tsx, src/components/SideMenu/SideMenu.module.scss, src/components/Tag/Tag.module.scss, src/pages/dashboard/[id]/components/Column/Column.module.scss, src/pages/dashboard/[id]/components/Column/index.tsx, src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss, src/styles/globals.scss, src/styles/text.scss
- #103 
style/textline -> develop
- 텍스트 길이 스타일 작업
- 컬럼 관리, 생성 모달, 할 일 모달 켤 시 스크롤 방지 작업
- 할 일 모달 반응형 수정
화이팅!
=> [fix] 텍스트 길이 및 모달 수정

src/components/Modal/DeleteModal/DeleteColumnModal.module.scss, src/components/Modal/ManageColumnModal/ManageColumnModal.module.scss
- #115 
fix/delete-modal -> develop
삭제 모달 반응형 수정
=> [style] 삭제 모달 스타일 작업

src/components/Modal/Comment/Comment.tsx, src/components/Modal/Modal/Modal.module.scss, src/components/Modal/Modal/index.tsx, src/components/Modal/ModalPopOver/index.tsx, src/components/Modal/ToDoModal/index.tsx
- #26 
- 모달 스크롤, 댓글 추가 기능 수정
- 왜 엔터 눌러서 한글 댓글 달 때만 댓글이 2개씩 등록 되는지 알 수 없네
=> [#26] chore: 자잘한 수정

src/components/Card/Card.module.scss, src/components/Card/index.tsx, src/components/Modal/ToDoModal/index.tsx, src/pages/mydashboard/components/SearchDashboard/index.tsx
- #120 
feat/invuted-search -> develop
처음 공백 입력 시 공백 제거
=> [fix] 초대 받은 목록 검색 수정

src/components/Modal/EditToDoModal/index.tsx, src/pages/dashboard/[id]/components/Column/index.tsx
- #123 
fix/edit-todo-modal ->dev
한글 태그 입력 시 함수가 두번 호출되는 현상 수정
카드 생성 오류 수정
=> [fix] editTioDo modal 버그 수정

src/components/Header/DashBoard/DashBoardHeader.module.scss
- #127 
style/profile-color
헤더 프로필 팝오버 글자색
감사합니다!
=> [style] 헤더 프로필 팝오버 글자색

src/components/Card/index.tsx, src/pages/login/Login.module.scss, src/pages/signup/Signup.module.scss
fix/perf
대시보드 페이지 카드 이미지 lazy loading 추가
로그인, 회원가입 페이지 여백 조정
=> [fix] 대시보드 페이지 카드 이미지 lazy loading 추가
